[package]
name = "rusty-ai"
version = "0.1.0"
authors = ["Robert Pyke <robert.j.pyke@gmail.com>"]
edition = "2018"


[dependencies]
specs = "0.16.1"
specs-derive = "0.4"
rand = "0.8.3"

[dependencies.sdl2]
version = "0.34.3"
default-features = false
features = ["image", "ttf"]